// Code generated by command: go run main.go -out ../../sigmoid_simd_amd64.s -stubs ../../sigmoid_simd_stub_gen_amd64.go -pkg tensor. DO NOT EDIT.

package tensor

// sigmoidF32AVX2 computes out[i] = 1/(1+exp(-in[i])) for the first n (multiple of 8)
// float32 lanes using an AVX2+FMA Cephes expf approximation. The caller handles any
// sub-8 remainder in Go.
//
//go:noescape
func sigmoidF32AVX2(out []float32, in []float32, n int)
