// Code generated by command: go run main.go -out ../../sigmoid_simd_amd64.s -stubs ../../sigmoid_simd_stub_gen_amd64.go -pkg tensor. DO NOT EDIT.

#include "textflag.h"

// func sigmoidF32AVX2(out []float32, in []float32, n int)
// Requires: AVX, AVX2, FMA3
TEXT ·sigmoidF32AVX2(SB), NOSPLIT, $0-56
	MOVQ         out_base+0(FP), AX
	MOVQ         in_base+24(FP), CX
	MOVQ         n+48(FP), DX
	SHRQ         $0x03, DX
	VBROADCASTSS sigf32_80000000<>+0(SB), Y0

loop:
	CMPQ         DX, $0x00
	JE           done
	VMOVUPS      (CX), Y1
	VXORPS       Y0, Y1, Y1
	VBROADCASTSS sigf32_42b0c0a5<>+0(SB), Y2
	VMINPS       Y2, Y1, Y1
	VBROADCASTSS sigf32_c2b0c0a5<>+0(SB), Y2
	VMAXPS       Y2, Y1, Y1
	VBROADCASTSS sigf32_3fb8aa3b<>+0(SB), Y2
	VMULPS       Y2, Y1, Y2
	VBROADCASTSS sigf32_3f000000<>+0(SB), Y3
	VADDPS       Y3, Y2, Y2
	VROUNDPS     $0x01, Y2, Y2
	VBROADCASTSS sigf32_3f318000<>+0(SB), Y3
	VFNMADD231PS Y3, Y2, Y1
	VBROADCASTSS sigf32_b95e8083<>+0(SB), Y3
	VFNMADD231PS Y3, Y2, Y1
	VMULPS       Y1, Y1, Y3
	VBROADCASTSS sigf32_39506967<>+0(SB), Y4
	VMULPS       Y1, Y4, Y4
	VBROADCASTSS sigf32_3ab743ce<>+0(SB), Y5
	VADDPS       Y5, Y4, Y4
	VMULPS       Y1, Y4, Y4
	VBROADCASTSS sigf32_3c088908<>+0(SB), Y5
	VADDPS       Y5, Y4, Y4
	VMULPS       Y1, Y4, Y4
	VBROADCASTSS sigf32_3d2aa9c1<>+0(SB), Y5
	VADDPS       Y5, Y4, Y4
	VMULPS       Y1, Y4, Y4
	VBROADCASTSS sigf32_3e2aaaaa<>+0(SB), Y5
	VADDPS       Y5, Y4, Y4
	VMULPS       Y1, Y4, Y4
	VBROADCASTSS sigf32_3f000000<>+0(SB), Y5
	VADDPS       Y5, Y4, Y4
	VMULPS       Y3, Y4, Y4
	VADDPS       Y1, Y4, Y4
	VBROADCASTSS sigf32_3f800000<>+0(SB), Y1
	VADDPS       Y1, Y4, Y4
	VCVTTPS2DQ   Y2, Y1
	VPBROADCASTD sigi32_0000007f<>+0(SB), Y2
	VPADDD       Y2, Y1, Y1
	VPSLLD       $0x17, Y1, Y1
	VMULPS       Y1, Y4, Y4
	VBROADCASTSS sigf32_3f800000<>+0(SB), Y1
	VADDPS       Y1, Y4, Y2
	VDIVPS       Y2, Y1, Y1
	VMOVUPS      Y1, (AX)
	ADDQ         $0x20, CX
	ADDQ         $0x20, AX
	DECQ         DX
	JMP          loop

done:
	VZEROUPPER
	RET

DATA sigf32_80000000<>+0(SB)/4, $0x80000000
GLOBL sigf32_80000000<>(SB), RODATA|NOPTR, $4

DATA sigf32_42b0c0a5<>+0(SB)/4, $0x42b0c0a5
GLOBL sigf32_42b0c0a5<>(SB), RODATA|NOPTR, $4

DATA sigf32_c2b0c0a5<>+0(SB)/4, $0xc2b0c0a5
GLOBL sigf32_c2b0c0a5<>(SB), RODATA|NOPTR, $4

DATA sigf32_3fb8aa3b<>+0(SB)/4, $0x3fb8aa3b
GLOBL sigf32_3fb8aa3b<>(SB), RODATA|NOPTR, $4

DATA sigf32_3f000000<>+0(SB)/4, $0x3f000000
GLOBL sigf32_3f000000<>(SB), RODATA|NOPTR, $4

DATA sigf32_3f318000<>+0(SB)/4, $0x3f318000
GLOBL sigf32_3f318000<>(SB), RODATA|NOPTR, $4

DATA sigf32_b95e8083<>+0(SB)/4, $0xb95e8083
GLOBL sigf32_b95e8083<>(SB), RODATA|NOPTR, $4

DATA sigf32_39506967<>+0(SB)/4, $0x39506967
GLOBL sigf32_39506967<>(SB), RODATA|NOPTR, $4

DATA sigf32_3ab743ce<>+0(SB)/4, $0x3ab743ce
GLOBL sigf32_3ab743ce<>(SB), RODATA|NOPTR, $4

DATA sigf32_3c088908<>+0(SB)/4, $0x3c088908
GLOBL sigf32_3c088908<>(SB), RODATA|NOPTR, $4

DATA sigf32_3d2aa9c1<>+0(SB)/4, $0x3d2aa9c1
GLOBL sigf32_3d2aa9c1<>(SB), RODATA|NOPTR, $4

DATA sigf32_3e2aaaaa<>+0(SB)/4, $0x3e2aaaaa
GLOBL sigf32_3e2aaaaa<>(SB), RODATA|NOPTR, $4

DATA sigf32_3f800000<>+0(SB)/4, $0x3f800000
GLOBL sigf32_3f800000<>(SB), RODATA|NOPTR, $4

DATA sigi32_0000007f<>+0(SB)/4, $0x0000007f
GLOBL sigi32_0000007f<>(SB), RODATA|NOPTR, $4
